pypi-oauthlib: Autospec creation for update from version 3.2.2 to version 3.3.0
Asif Saif Uddin (7):
      create security policy
      draft CI
      Create dependency-review.yml
      Update .github/workflows/python-publish.yml
      create security policy
      Update supported python versions in classifier
      Update .github/workflows/dependency-review.yml

Burke Livingston (2):
      Update pre-configured OIDC server to use OIDC flavor of Refresh Token grant type (#838)
      Update pre-configured OIDC server to use OIDC flavor of Refresh Token grant type (#838)

Christian Clauss (11):
      Upgrade GitHub Actions and make bandit, codespell, and pytest mandatory (#835)
      Fix failing GitHub Action lint_python.yml
      Upgrade GitHub Actions and make bandit, codespell, and pytest mandatory (#835)
      Fix failing GitHub Action lint_python.yml
      Lint with ruff to replace bandit, flake8, isort, pyupgrade (#855)
      Lint with ruff to replace bandit, flake8, isort, pyupgrade
      Tox use ruff (#864)
      Update python-build.yml
      ruff --output-format=github
      Codespell
      Update lint_python.yml

Erich Seifert (1):
      Add classifier for Python 3.11

Everton Seiei Arakaki (1):
      license: remove generic classifier (#895)

Hugo van Kemenade (3):
      Add support for Python 3.12 (#859)
      CI: Only attempt upload for upstream
      thedrow

Jaap Roes (1):
      Guard ui_locales.split() (#879)

Jonathan Huot (37):
      Add 3.2.2 version
      Update .github/workflows/python-publish.yml
      Initial build & publish rules with GH Actions
      Add 3.2.2 version
      Add graphviz to generate dot graphs in docs
      Remove unnecessary name
      Changed build badge in README
      Fix Build Badge URL
      Add dependency with CVE to trigger security check
      Trigger security check failure
      Revert "Trigger security check failure"
      Revert "Add dependency with CVE to trigger security check"
      Bump actions/checkout
      Removed obsolete versions in documentation
      Fix latest ruff findings
      Removed year from license
      Removed unused bandit, since it has been replaced with ruff
      Removed inactive users while keeping them in AUTHORS file.
      Refresh wording of license to not confuse tools between BSD-3 & BSD
      Add 3.3.0 changelog and bump version
      Fix multiple if statements
      Handle expires_at with best effort basis
      Removed version ping to work with all py versions
      Simplified str convertion of expires_at
      Does not round if float is provided
      Factorized parsing of expires_at
      Added expires_at changelog
      Removed unnecessary comments
      Simplify isinstance calls to one/Ruff/SIM101
      Updated release date
      Bumped release
      Updated GH actions
      Added maintainer instructions
      Fixed ruff findings about function import
      Fix linter after rebase
      Updated recommended filter for publish
      Execute publish workflow of the tagged source. Not of master branch.

Maximilian Wirtz (2):
      Use proper SPDX identifier
      Use proper SPDX identifier

Michał Górny (2):
      Update setup.cfg to use license_files (#839)
      Update setup.cfg to use license_files (#839)

Miro Hrončok (1):
      Make UtilsTests.test_filter_params Python 3.13+ compatible

Raymond Penners (2):
      docs: add django-allauth to available options
      docs: add django-allauth to available options

Shawn Zivontsis (3):
      Fix CI Errors (#878)
      Update create_code_verifier to output the proper length (#876)
      Remove code verifier regex (#893)

Sindri Guðmundsson (2):
      Ensure expires_at is always int
      Ensure expires_at is always int

Theron Luhn (1):
      Ensure that `request.client_id` is set during Refresh Token Grant.

Tiphaine LAURENT (2):
      OAuth2Error: Allow falsy values as state
      OAuth2Error: Allow falsy values as state

david uzumaki (4):
      thedrow
      Allow user_code to be configured for device auth flow (Device Authorization Grant) (#885)
      Add DeviceCodeGrant type for device code flow(rfc8628) section 3.4 & 3.5  (#889)
      Device flow: Pass verification_uri_complete to endpoint + pass Server kwargs to DeviceCodeGrant to allow validators to be setup with more flexibility (#891)